[C++] fix STL header includes for NodeImpl.cc and Stream.cc (#3471)
MSVC complains about missing symbols:

```
lang/c++/impl/Stream.cc(183): error C2039: 'back_inserter': is not a member of 'std'
lang/c++/impl/Stream.cc(183): error C3861: 'back_inserter': identifier not found
```

Signed-off-by: Stephan Lachnit <stephanlachnit@debian.org>